### PR TITLE
Fixes #1617: Federation Enum not parsing value 0

### LINKED ISSUE #1617: Federation Enum not parsing value 0, works other values
# Enums fail to resolve correctly with a value of 0, when using Federation.

## Versions:
```
    "@apollo/federation": "^0.9.4",
    "apollo-server": "^2.9.3",
    "graphql": "^14.1.1",
    "graphql-tools": "^4.0.4"
```

## Example Repo:
https://github.com/postman-nz/gql-federation-issue

### Server Code:
```
const { ApolloServer, gql } = require("apollo-server");
const { buildFederatedSchema } = require("@apollo/federation");

const typeDefs = gql`
  type Query {
    colorBad: AllowedColor
    colorGood: AllowedColor
  }

  enum AllowedColor {
    RED
    GREEN
    BLUE
  }
`;

const resolvers = {
  Query: {
    colorBad: () => 0,
    colorGood: () => 1
  },
  AllowedColor: {
    RED: 0,
    GREEN: 1,
    BLUE: 2
  }
};

// Works with this server
/*
const server = new ApolloServer({
  typeDefs,
  resolvers
});
*/
const server = new ApolloServer({
  schema: buildFederatedSchema({
    typeDefs,
    resolvers
  })
});

server.listen().then(({ url }) => {
  console.log(`🚀  Server ready at ${url}`);
});
```

### Success when running the Query
```
query {
  colorGood
}
```
We get the expected result.
```
{
  "data": {
    "colorGood": "GREEN"
  }
}
```

###  Failure when running the query 
```
query {
  colorBad
}
```
An error is returned: `"Expected a value of type \"AllowedColor\" but received: 0"`

#### Expected Behavior:
```
{
  "data": {
    "colorBad": "RED"
  }
}
```
*If Federation is removed, both of the queries run as expected.*

### PR DESCRIPTION
**Pull request by postman-nz**
Fixes https://github.com/apollographql/apollo-tooling/issues/1617

Updated buildSchemaFromSDL to handle enums with a value of 0. Previously, when an enum had a value of 0, the name would be used as the enum value.

Added a unit test to ensure 0 is parsed correctly.

TODO:

- [X] Update CHANGELOG.md\* with your change (include reference to issue & this PR)
- [X] Make sure all of the significant new logic is covered by tests
- [X] Rebase your changes on master so that they can be merged easily
- [X] Make sure all tests and linter rules pass

### CODE REVIEW

**Comment by postman-nz** [comment]
I'm working on the CLA, just need to confirm with my employer that it's ok to sign.

**Comment by marjorg** [comment]
@postman-nz We ran into the same issues with our Federations, did you get around to signing the CLA so the PR can proceed?

**Comment by postman-nz** [comment]
@marjorg Yes I have signed the CLA, and completed all the requirements for the PR to pass.

As a workaround, we hard coded all our 0 enum values to -1 (assuming -1 isn't being used), and in our resolvers added a check:
`if(model.enumValue == 0) model.enumValue = -1`

Which works for now, but it's not a long term solution.

**Comment by postman-nz** [comment]
Hi @lilyball @alloy is there anything else I need to do to get this PR reviewed?

We're creating a lot of tech debt trying to work around the bug.

File: packages/apollo-graphql/src/schema/buildSchemaFromSDL.ts [hunk 1]
```diff
@@ -237,7 +237,10 @@ export function addResolversToSchema(
       const values = type.getValues();
       const newValues: { [key: string]: GraphQLEnumValue } = {};
       values.forEach(value => {
-        const newValue = (fieldConfigs as any)[value.name] || value.name;
+        let newValue = (fieldConfigs as any)[value.name];
+        if (newValue == undefined) {
```
Comment (lilyball) [inline packages/apollo-graphql/src/schema/buildSchemaFromSDL.ts]: This should probably be `===`

Comment (postman-nz) [reply packages/apollo-graphql/src/schema/buildSchemaFromSDL.ts]: Thanks @lilyball, I have updated. I do have a repo that shows the problem, but as you can tell it's quite a small fix.

**Comment by postman-nz** [comment]
Hi @JakeDawkins and  @jbaxleyiii, 

Is there anything else I have to do to get this PR completed?  (I'm new to contributing to public repos, so not 100% sure on the process)

Thanks!

**Comment by JakeDawkins** [comment]
Hey @postman-nz! So sorry for letting this slip through the cracks. Everything looks good to me! Can you rebase this branch off master? My `Update Branch` button isn't working for some reason 🤔

**Comment by postman-nz** [comment]
> 
> 
> Hey @postman-nz! So sorry for letting this slip through the cracks. Everything looks good to me! Can you rebase this branch off master? My `Update Branch` button isn't working for some reason 🤔

No problem mate! I have rebased with master (I hope 😄). Let me know if there is anything else you'd like me to do.
