### PR TITLE
swift: Fix code generation for null input fields

### LINKED ISSUE #1592: Swift: Can't specify null in query
**Intended outcome:**
Works correctly.

**Actual outcome:**
Codegen error:
```
→ Cannot read property 'kind' of null
TypeError: Cannot read property 'kind' of null
    at expressionFromValue (path/Pods/Apollo/scripts/apollo/node_modules/apollo-codegen-swift/lib/helpers.js:159:23)
    at language_1.SwiftSource.wrap.language_1.SwiftSource.join.Object.entries.map (path/Pods/Apollo/scripts/apollo/node_modules/apollo-codegen-swift/lib/helpers.js:167:87)
    at Array.map (<anonymous>)
    at expressionFromValue (path/Pods/Apollo/scripts/apollo/node_modules/apollo-codegen-swift/lib/helpers.js:166:124)
    at language_1.SwiftSource.wrap.language_1.SwiftSource.join.args.map.arg (path/Pods/Apollo/scripts/apollo/node_modules/apollo-codegen-swift/lib/helpers.js:178:84)
    at Array.map (<anonymous>)
    at Helpers.dictionaryLiteralForFieldArguments (path/Pods/Apollo/scripts/apollo/node_modules/apollo-codegen-swift/lib/helpers.js:177:99)
    at withIndent (path/Pods/Apollo/scripts/apollo/node_modules/apollo-codegen-swift/lib/codeGeneration.js:499:79)
    at GeneratedFile.withIndent (path/Pods/Apollo/scripts/apollo/node_modules/apollo-codegen-core/lib/utilities/CodeGenerator.js:54:9)
    at SwiftAPIGenerator.withIndent (path/Pods/Apollo/scripts/apollo/node_modules/apollo-codegen-core/lib/utilities/CodeGenerator.js:109:26)
```

**How to reproduce the issue:**
This should help in making a testcase.
```
const schema = buildSchema(`
         schema {
           query: Query
         }
         type Query {
           foo(input: FooInput!): Int
         }
         input FooInput {
           id: ID
         }
       `);
       const document = parse(`
         query FieldArgumentsWithEmptyInputObject {
           foo(input: { id: null }) {
             id
           }
         }
       `);
```

### PR DESCRIPTION
**Pull request by lilyball**
Also add a test that covers all scalar types just in case.

Fixes #1592

TODO:

- [x] Update CHANGELOG.md\* with your change (include reference to issue & this PR)
- [X] Make sure all of the significant new logic is covered by tests
- [X] Rebase your changes on master so that they can be merged easily
- [X] Make sure all tests and linter rules pass

### CODE REVIEW

File: packages/apollo-codegen-swift/src/helpers.ts [hunk 1]
```diff
@@ -255,7 +255,9 @@ export class Helpers {
 
   dictionaryLiteralForFieldArguments(args: Argument[]): SwiftSource {
     function expressionFromValue(value: any): SwiftSource {
-      if (value.kind === "Variable") {
+      if (value === null) {
+        return swift`nil`;
```
Comment (lilyball) [inline packages/apollo-codegen-swift/src/helpers.ts]: I'm assuming here that we want a literal `nil` in the result map instead of e.g. `NSNull()`, since the `ResultMap`'s type is `[String: Any?]`. That said, I haven't tested this change in the context of a full project, just the unit test as given.

@cltnschlosser I would appreciate it if you could test this with your full project.

Comment (cltnschlosser) [reply packages/apollo-codegen-swift/src/helpers.ts]: Yeah, I think `nil` makes sense. I didn’t actually use this in a project. I had discovered it when trying to workaround the other issue. I think we just need to verify that the resulting JSON has the null value. I can do that tomorrow.

**Comment by lilyball** [comment]
Oops I didn't update the changelog after creating the PR. I'll do that tomorrow.

File: packages/apollo-codegen-swift/src/helpers.ts (hunk 1 above)
Comment (cltnschlosser) [reply packages/apollo-codegen-swift/src/helpers.ts]:
```
{
	"operationName": "Test",
	"query": "query Test {\n  employee(request: {id: null}) {\n    __typename\n    fullName\n  }\n}",
	"variables": null
}
```

Seems to work, and graphql-faker was fine with the request.

**Comment by lilyball** [comment]
Updated changelog (and rebased for good measure).
